# set port server
server:
  port: 9000

spring:
  # set name app
  application:
    name: Server App
  # setup database connection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/sibkm_serverapp_07
    username: fuzi
    password: kucing
  # setup hibernate jpa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: metrodataacedemy@gmail.com
    password: hbnd wnis ehnr arhh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    user:
      name: user
      password: user
